[2024-09-20 01:18:53,014:INFO:__init__:Logging setup complete. Logs will be written to: logs\running_logs.log:]
[2024-09-20 01:18:53,014:INFO:__init__:This is a test log message.:]
[2024-09-20 01:19:15,571:INFO:__init__:Logging setup complete. Logs will be written to: logs\running_logs.log:]
[2024-09-20 01:19:15,571:INFO:__init__:This is a test log message.:]
[2024-09-20 01:19:15,576:INFO:main:Welcome to my custom logs!:]
[2024-09-20 22:21:21,237:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:21:21,253:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:24:08,850:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:24:08,852:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:24:57,332:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:24:57,335:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:25:42,229:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:25:42,232:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:27:22,049:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:27:22,052:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:29:44,037:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:29:44,040:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:31:06,183:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:31:06,189:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:33:54,805:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:33:54,811:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:34:50,961:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:34:50,964:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:35:01,937:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:35:01,939:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:35:18,089:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:35:18,091:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:35:34,336:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:35:34,351:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:36:43,718:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:36:43,723:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:38:28,408:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:38:28,411:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:39:43,306:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:39:43,308:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:40:05,062:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:40:05,065:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:40:18,051:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:40:18,055:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:45:14,980:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:45:14,983:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:52:03,532:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:52:03,534:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:52:25,387:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:52:25,424:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:52:56,594:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:52:56,599:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:53:23,584:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:53:23,588:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 22:59:13,861:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 22:59:13,866:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:00:35,188:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:00:35,194:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:00:47,898:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:00:47,905:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:01:40,908:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:01:40,912:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:02:16,704:INFO:3104699686:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D3E7:1133:13868E:13FE55:66EDB890
Accept-Ranges: bytes
Date: Fri, 20 Sep 2024 18:01:56 GMT
Via: 1.1 varnish
X-Served-By: cache-fjr990023-FJR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1726855313.272601,VS0,VE2918
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 25a3ce8bffebe765d247c5a457491619e3a966a5
Expires: Fri, 20 Sep 2024 18:06:56 GMT
Source-Age: 2

:]
[2024-09-20 23:02:46,348:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:02:46,351:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:02:46,352:INFO:3104699686:File already exists of size: get_size(Path(self.config.local_data_file)):]
[2024-09-20 23:03:41,180:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:03:41,182:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:05:05,723:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:05:05,726:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:05:16,733:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:05:16,736:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:05:16,739:INFO:337096913:11345:]
[2024-09-20 23:05:16,740:INFO:337096913:File already exists of size: get_size(Path(self.config.local_data_file)):]
[2024-09-20 23:05:57,851:INFO:common:yaml file: config\config.yaml loaded successfully.:]
[2024-09-20 23:05:57,854:INFO:common:yaml file: params.yaml loaded successfully.:]
[2024-09-20 23:05:57,856:INFO:43553147:File already exists of size: 11345 KB:]
[2024-09-20 23:31:19,282:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-20 23:31:19,287:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-20 23:31:19,287:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-20 23:31:19,287:INFO:data_ingestion:File already exists of size: 11345 KB:]
[2024-09-20 23:31:19,787:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-20 23:31:37,385:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-20 23:31:37,390:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-20 23:31:37,390:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-20 23:31:40,092:ERROR:main:[Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip':]
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\main.py", line 9, in <module>
    obj.main()
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\src\cnnClassifier\components\data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\envs\chickDis\Lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-09-20 23:34:00,451:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-20 23:34:00,456:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-20 23:34:00,456:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-20 23:34:34,193:INFO:data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D3E7:1133:13868E:13FE55:66EDB890
Accept-Ranges: bytes
Date: Fri, 20 Sep 2024 18:34:13 GMT
Via: 1.1 varnish
X-Served-By: cache-fjr990022-FJR
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1726857254.790930,VS0,VE11
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0286d7d45e7447abc668ca816ae7ca6764a3d115
Expires: Fri, 20 Sep 2024 18:39:13 GMT
Source-Age: 143

:]
[2024-09-20 23:34:34,743:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 12:04:53,928:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:04:53,938:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:07:51,677:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:12:10,663:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:12:10,667:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:12:11,556:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:12:12,104:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:12:56,658:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:12:56,671:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:12:57,658:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:12:58,117:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:21:09,407:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-21 12:21:09,413:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:21:09,421:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:21:45,729:INFO:data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6F48:10DD:33AC9F8:359E3A7:66EE73F2
Accept-Ranges: bytes
Date: Sat, 21 Sep 2024 07:21:25 GMT
Via: 1.1 varnish
X-Served-By: cache-fjr990027-FJR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1726903283.208884,VS0,VE2385
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e8f56bf01a2ee745684a8781d7298e333f2adc03
Expires: Sat, 21 Sep 2024 07:26:25 GMT
Source-Age: 2

:]
[2024-09-21 12:21:46,568:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 12:21:46,569:INFO:main:*********************:]
[2024-09-21 12:21:46,576:INFO:main:>>>> stage Prepare Base Model Stage started <<<<<:]
[2024-09-21 12:21:46,579:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:21:46,585:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:21:47,586:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:21:47,897:ERROR:main:module 'keras._tf_keras.keras.layers' has no attribute 'flatten':]
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\main.py", line 22, in <module>
    obj.main()
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepar_base_model.update_base_model()
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\src\cnnClassifier\components\prepare_base_model.py", line 52, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\src\cnnClassifier\components\prepare_base_model.py", line 30, in _prepare_full_model
    flatten_in = tf.keras.layers.flatten()(model.output)
                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'flatten'
[2024-09-21 12:22:23,345:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-21 12:22:23,360:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:22:23,364:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:22:23,366:INFO:data_ingestion:File already exists of size: 11345 KB:]
[2024-09-21 12:22:23,804:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 12:22:23,817:INFO:main:*********************:]
[2024-09-21 12:22:23,819:INFO:main:>>>> stage Prepare Base Model Stage started <<<<<:]
[2024-09-21 12:22:23,821:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 12:22:23,824:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 12:22:24,607:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:22:25,226:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 12:22:25,435:INFO:main:>>>> stage Prepare Base Model Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 13:04:48,002:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 13:04:48,006:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 13:04:48,010:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 13:04:48,015:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 13:06:44,172:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 13:06:44,172:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 13:06:44,180:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 13:06:44,180:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 13:06:53,279:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 13:06:53,288:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 13:06:53,292:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 13:06:53,297:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 21:36:00,731:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 21:36:00,737:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 21:36:00,739:INFO:common:created directory at: artifacts:]
[2024-09-21 21:36:00,742:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 21:36:00,744:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 21:36:00,747:INFO:common:created directory at: artifacts\training:]
[2024-09-21 21:36:01,494:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-09-21 21:43:07,436:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 21:43:07,448:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 21:43:09,337:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 21:43:09,858:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 21:43:34,862:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 21:43:34,875:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 21:43:34,884:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 21:43:34,887:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 21:43:52,638:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 21:43:52,646:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 21:43:52,648:INFO:common:created directory at: artifacts:]
[2024-09-21 21:43:52,650:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 21:43:52,653:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 21:43:52,654:INFO:common:created directory at: artifacts\training:]
[2024-09-21 21:43:53,534:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-09-21 21:48:16,301:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 21:48:16,317:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 21:48:16,325:INFO:common:created directory at: artifacts:]
[2024-09-21 21:48:16,337:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 21:48:16,347:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 21:48:16,354:INFO:common:created directory at: artifacts\training:]
[2024-09-21 21:48:17,159:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-09-21 21:49:17,901:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 21:49:17,914:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 21:49:17,918:INFO:common:created directory at: artifacts:]
[2024-09-21 21:49:17,923:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 21:49:17,927:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 21:49:17,931:INFO:common:created directory at: artifacts\training:]
[2024-09-21 21:49:18,802:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-09-21 21:51:36,418:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:13:09,592:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-21 22:13:09,608:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:13:09,608:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:13:28,541:INFO:data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5584:2CF0F4:2CAA2A:357384:66EEFEA7
Accept-Ranges: bytes
Date: Sat, 21 Sep 2024 17:13:13 GMT
Via: 1.1 varnish
X-Served-By: cache-qpg1277-QPG
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1726938792.109680,VS0,VE1070
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: bb7576037f7a35a20fd3c6e58ccf3965f8ec28a9
Expires: Sat, 21 Sep 2024 17:18:13 GMT
Source-Age: 1

:]
[2024-09-21 22:13:29,259:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:13:29,259:INFO:main:*********************:]
[2024-09-21 22:13:29,259:INFO:main:>>>> stage Prepare Base Model Stage started <<<<<:]
[2024-09-21 22:13:29,281:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:13:29,281:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:13:30,177:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:13:30,571:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:13:30,699:INFO:main:>>>> stage Prepare Base Model Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:13:30,699:INFO:main:>>>> stage Training Stage started <<<<<:]
[2024-09-21 22:13:30,715:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:13:30,715:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:13:30,715:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 22:13:30,715:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 22:13:30,715:INFO:configuration:Returning prepare callback config:]
[2024-09-21 22:13:30,715:INFO:common:created directory at: artifacts\training:]
[2024-09-21 22:13:30,715:ERROR:main:Training.__init__() got an unexpected keyword argument 'config':]
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\main.py", line 36, in <module>
    obj.main()
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    training = Training(config=training_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Training.__init__() got an unexpected keyword argument 'config'
[2024-09-21 22:16:47,659:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-21 22:16:47,674:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:16:47,674:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:16:47,674:INFO:data_ingestion:File already exists of size: 11345 KB:]
[2024-09-21 22:16:48,096:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:16:48,096:INFO:main:*********************:]
[2024-09-21 22:16:48,096:INFO:main:>>>> stage Prepare Base Model Stage started <<<<<:]
[2024-09-21 22:16:48,096:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:16:48,096:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:16:48,580:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:16:49,138:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:16:49,305:INFO:main:>>>> stage Prepare Base Model Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:16:49,305:INFO:main:>>>> stage Training Stage started <<<<<:]
[2024-09-21 22:16:49,305:ERROR:main:Training.__init__() missing 1 required positional argument: 'config':]
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Chicken Disease Classification\Chicken-Disease-Classification-MLOps-Approach\main.py", line 35, in <module>
    obj = Training()
          ^^^^^^^^^^
TypeError: Training.__init__() missing 1 required positional argument: 'config'
[2024-09-21 22:17:52,720:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-21 22:17:52,720:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:17:52,720:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:17:52,735:INFO:data_ingestion:File already exists of size: 11345 KB:]
[2024-09-21 22:17:53,126:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:17:53,126:INFO:main:*********************:]
[2024-09-21 22:17:53,126:INFO:main:>>>> stage Prepare Base Model Stage started <<<<<:]
[2024-09-21 22:17:53,126:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:17:53,126:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:17:53,610:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:17:53,982:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:17:54,182:INFO:main:>>>> stage Prepare Base Model Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:17:54,182:INFO:main:>>>> stage Training Stage started <<<<<:]
[2024-09-21 22:17:54,198:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:17:54,198:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:17:54,214:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 22:17:54,214:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 22:17:54,214:INFO:configuration:Returning prepare callback config:]
[2024-09-21 22:17:54,214:INFO:common:created directory at: artifacts\training:]
[2024-09-21 22:17:54,553:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-09-21 22:18:36,072:INFO:main:>>>> stage Data Ingestion Stage started <<<<<:]
[2024-09-21 22:18:36,076:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:18:36,077:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:18:48,102:INFO:data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5584:2CF0F4:2CAA2A:357384:66EEFEA7
Accept-Ranges: bytes
Date: Sat, 21 Sep 2024 17:18:38 GMT
Via: 1.1 varnish
X-Served-By: cache-qpg120085-QPG
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1726939119.511123,VS0,VE333
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e6ce76a38196e1f917d8f1945abae17d56ff85dd
Expires: Sat, 21 Sep 2024 17:23:38 GMT
Source-Age: 0

:]
[2024-09-21 22:18:49,616:INFO:main:>>>> stage Data Ingestion Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:18:49,617:INFO:main:*********************:]
[2024-09-21 22:18:49,619:INFO:main:>>>> stage Prepare Base Model Stage started <<<<<:]
[2024-09-21 22:18:49,626:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:18:49,632:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:18:50,342:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:18:50,615:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:18:50,724:INFO:main:>>>> stage Prepare Base Model Stage completed <<<<< 
 
 x=========x:]
[2024-09-21 22:18:50,724:INFO:main:>>>> stage Training Stage started <<<<<:]
[2024-09-21 22:18:50,729:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2024-09-21 22:18:50,733:INFO:common:yaml file: params.yaml loaded successfully:]
[2024-09-21 22:18:50,737:INFO:common:created directory at: artifacts\prepare_callbacks\checkpoint_dir:]
[2024-09-21 22:18:50,738:INFO:common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir:]
[2024-09-21 22:18:50,739:INFO:configuration:Returning prepare callback config:]
[2024-09-21 22:18:50,741:INFO:common:created directory at: artifacts\training:]
[2024-09-21 22:18:50,969:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-09-21 22:20:19,450:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. :]
[2024-09-21 22:20:19,578:INFO:main:>>>> stage Training Stage completed <<<<< 
 
 x=========x:]
